### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by niceandneat** [niceandneat/yugioh-deck-manager#1]
- [ ] Edit cards in deck
- [ ] Show Differences from previous ban
- [ ] Better facet filtering (like [this](https://tanstack.com/table/v8/docs/examples/react/filters))
- [ ] Support other file import (master dual json, plain card name&counts text, bulk import...)
- [ ] Support unofficial cards
- [ ] Standalone executables (waiting [nextron](https://github.com/saltyshiomix/nextron) to support Next.js 13.4+)
